from enum import Enum


class IntentType(str, Enum):
    """Enumeration of supported user intents for Teddy NLU and Level 7 AI Orchestrator."""

    # Stage 5 NLU Intents
    CREATE_HDFS_FILE = "CREATE_HDFS_FILE"
    EXPLAIN_HDFS = "EXPLAIN_HDFS"
    EXPLAIN_COMPONENT = "EXPLAIN_COMPONENT"
    EXPLAIN_BLOCKS = "EXPLAIN_BLOCKS"
    EXPLAIN_REPLICATION = "EXPLAIN_REPLICATION"
    SIMULATE_FAILURE = "SIMULATE_FAILURE"
    RECOVER_DATANODE = "RECOVER_DATANODE"
    PAUSE_SIMULATION = "PAUSE_SIMULATION"
    RESUME_SIMULATION = "RESUME_SIMULATION"
    RESET_SIMULATION = "RESET_SIMULATION"
    UNKNOWN = "UNKNOWN"

    # Legacy / Level 7 AI Orchestrator Intents
    EXPLAIN = "EXPLAIN"
    START_SIMULATION = "START_SIMULATION"
    MODIFY_SIMULATION = "MODIFY_SIMULATION"
    ASK_QUESTION = "ASK_QUESTION"
    PAUSE = "PAUSE"
    STOP = "STOP"
    RESUME = "RESUME"
    RESTART = "RESTART"
    COMPARE = "COMPARE"
    FAILURE_INJECTION = "FAILURE_INJECTION"
    SCALE = "SCALE"
    ZOOM = "ZOOM"
    SHOW_COMPONENT = "SHOW_COMPONENT"
    QUIZ = "QUIZ"
