from enum import Enum


class DataNodeStatus(str, Enum):
    LIVE = "LIVE"
    FAILED = "FAILED"
    DECOMMISSIONED = "DECOMMISSIONED"


class HeartbeatStatus(str, Enum):
    HEALTHY = "HEALTHY"
    MISSED = "MISSED"


class BlockState(str, Enum):
    CREATED = "CREATED"
    REPLICATING = "REPLICATING"
    HEALTHY = "HEALTHY"
    UNDER_REPLICATED = "UNDER_REPLICATED"
    RECOVERING = "RECOVERING"
    LOST = "LOST"


class FileStatus(str, Enum):
    WRITING = "WRITING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class HDFSEventType(str, Enum):
    HDFS_CLUSTER_CREATED = "HDFS_CLUSTER_CREATED"
    FILE_WRITE_STARTED = "FILE_WRITE_STARTED"
    FILE_RECEIVED = "FILE_RECEIVED"
    FILE_SPLIT = "FILE_SPLIT"
    BLOCK_CREATED = "BLOCK_CREATED"
    BLOCK_PLACEMENT_STARTED = "BLOCK_PLACEMENT_STARTED"
    BLOCK_REPLICA_CREATED = "BLOCK_REPLICA_CREATED"
    NAMENODE_METADATA_UPDATED = "NAMENODE_METADATA_UPDATED"
    FILE_WRITE_COMPLETED = "FILE_WRITE_COMPLETED"

    FILE_READ_STARTED = "FILE_READ_STARTED"
    NAMENODE_LOOKUP = "NAMENODE_LOOKUP"
    BLOCK_LOCATIONS_FOUND = "BLOCK_LOCATIONS_FOUND"
    BLOCK_READ = "BLOCK_READ"
    FILE_READ_COMPLETED = "FILE_READ_COMPLETED"

    DATANODE_HEARTBEAT = "DATANODE_HEARTBEAT"
    DATANODE_FAILED = "DATANODE_FAILED"
    BLOCK_REPLICATION_DEGRADED = "BLOCK_REPLICATION_DEGRADED"
    BLOCK_MARKED_UNDER_REPLICATED = "BLOCK_MARKED_UNDER_REPLICATED"
    REPLICATION_STARTED = "REPLICATION_STARTED"
    REPLICA_RECOVERED = "REPLICA_RECOVERED"
    BLOCK_REPLICATION_RESTORED = "BLOCK_REPLICATION_RESTORED"

    BLOCK_MARKED_LOST = "BLOCK_MARKED_LOST"
    FILE_READ_FAILED = "FILE_READ_FAILED"

    SIMULATION_CONFIG_UPDATED = "SIMULATION_CONFIG_UPDATED"
    SIMULATION_RESTARTED = "SIMULATION_RESTARTED"
    DATANODE_ADDED = "DATANODE_ADDED"
    DATANODE_REMOVED = "DATANODE_REMOVED"
    SIMULATION_SPEED_CHANGED = "SIMULATION_SPEED_CHANGED"
